### Basic http request
GET http://localhost:3000/dataset1/commit1/banaan.jpg


### Retrieve image
GET http://localhost:3000/file/

### State example
GET http://localhost:3000/

### Multipart form
POST http://localhost:3000/upload
Content-Type: multipart/form-data; boundary=MyBoundary

--MyBoundary
Content-Disposition: form-data; name="file"; filename="cat.1.jpg"
Content-Type: image/jpeg

< data/train/cats/cat.1.jpg
--MyBoundary
Content-Disposition: form-data; name="ProspectId"

1
--MyBoundary
--

### Post new commit
POST http://localhost:3000/1 HTTP/1.1
content-type: application/json

{
    "hash": "2",
    "parent": "1",
    "branch": "master",
    "name": "Update 7-3",
    "desc": "Added extra cat photos",
    "diff": [
        {
            "change_type": "Add",
            "files": ["cat1.jpg", "cat2.jpg"]
        }
    ],
    "deprecated": false
}

### Create new dataset
POST http://localhost:3000/datasets/ HTTP/1.1
content-type: application/json

{
  "name": "Cat photos",
  "path": "cat_photos",
  "backend": {
    "LocalBackend": {
      "path": "./storage/"
    }
  },
  "description": "Very important cat photos."
}

### Delete dataset
DELETE http://localhost:3000/datasets/cat_photos/ HTTP/1.1