@address = http://localhost:3000
@dataset_path = test_dataset
@initial_commit_hash = initial_commit
@commit_hash = 4
@branch_hash = initial_branch
@file = cat.1.jpg

### Delete dataset
DELETE {{address}}/{{dataset_path}} HTTP/1.1

### Get dataset
GET {{address}}/{{dataset_path}} HTTP/1.1

### Create new dataset
POST {{address}}/ HTTP/1.1
content-type: application/json

{
  "name": "{{dataset_path}}",
  "backend": "Local",
  "credentials": {
      "path": "./storage/"
  },
  "description": "This dataset contains test images!"
}

### Get version tree
GET {{address}}/{{dataset_path}}/vtree HTTP/1.1

### Get a commit
GET {{address}}/{{dataset_path}}/commit/4iuDjHdn4ewSZC7fJtLWHzw083PLr5Eo HTTP/1.1

### Create new branch
POST {{address}}/{{dataset_path}}/branch HTTP/1.1
content-type: application/json

{
  "hash": "created_branch",
  "name": "CreatedBranch",
  "head": "mkQaqy7kM4ILbBmlSQECAmpK1xMk9fPS"
}


### Get a branch
GET {{address}}/{{dataset_path}}/branch/gGpK3w1mZyTaTC67v2ucd4MxrhMXg1Et HTTP/1.1

### Add a commit
POST {{address}}/{{dataset_path}}/commit
Content-Type: multipart/form-data; boundary=MyBoundary
Accept: application/json

preamble which should be ignored...
--MyBoundary
Content-Disposition: form-data; name="file"; filename="commit.json"
Content-Type: application/json

< data/commit.json

--MyBoundary
Content-Disposition: form-data; name="file"; filename="data/train/cats/cat.1.jpg/4"
Content-Type: image/jpeg

< data/train/cats/cat.1.jpg

--MyBoundary
Content-Disposition: form-data; name="file"; filename="data/train/cats/cat.2.jpg/4"
Content-Type: image/jpeg

< data/train/cats/cat.2.jpg

--MyBoundary--


### Add a commit with branch
POST {{address}}/{{dataset_path}}/commit
Content-Type: multipart/form-data; boundary=MyBoundary
Accept: application/json

preamble which should be ignored...
--MyBoundary
Content-Disposition: form-data; name="file"; filename="branch.json"
Content-Type: application/json

< data/branch.json
--MyBoundary
Content-Disposition: form-data; name="file"; filename="commit.json"
Content-Type: application/json

< data/commit.json

--MyBoundary
Content-Disposition: form-data; name="file"; filename="cat.1.jpg/4"
Content-Type: image/jpeg

< data/train/cats/cat.1.jpg

--MyBoundary
Content-Disposition: form-data; name="file"; filename="cat.2.jpg/4"
Content-Type: image/jpeg

< data/train/cats/cat.2.jpg

--MyBoundary--


### Add a commit octed stream
POST {{address}}/{{dataset_path}}/commit
Content-Type: multipart/form-data; boundary=MyBoundary
Accept: application/json

preamble which should be ignored...
--MyBoundary
Content-Disposition: form-data; name="file"; filename="commit.json"
Content-Type: application/octet-stream

< data/commit.json

--MyBoundary
Content-Disposition: form-data; name="file"; filename="cat.1.jpg/4"
Content-Type: application/octet-stream

< data/train/cats/cat.1.jpg

--MyBoundary
Content-Disposition: form-data; name="file"; filename="cat.2.jpg/4"
Content-Type: application/octet-stream

< data/train/cats/cat.2.jpg

--MyBoundary--


### Get a file
GET {{address}}/{{dataset_path}}/file/{{commit_hash}}/{{file}} HTTP/1.1

### Reset state
POST {{address}}/reset_state HTTP/1.1

