@address = http://localhost:3000
@dataset_path = cats-subset
@initial_commit_hash = initial_commit
@commit_hash = 4
@branch_hash = initial_branch
@file = cat.1.jpg

### Delete dataset
DELETE {{address}}/{{dataset_path}} HTTP/1.1

### Get dataset
GET {{address}}/{{dataset_path}} HTTP/1.1

### Get a list of datasets
GET {{address}}/ HTTP/1.1

### Get pipeline executions
GET {{address}}/{{dataset_path}}/pipelines HTTP/1.1

### Get pipeline executions
GET {{address}}/pipelines HTTP/1.1

### Get pipeline run
GET {{address}}/{{dataset_path}}/pipelines/ny84rq3vrpept5g5ufmikr3hpgfcorjd HTTP/1.1

### Get pipeline execution without dataset
GET {{address}}/pipelines/a HTTP/1.1

### Reset state
POST {{address}}/reset_state HTTP/1.1

### Get lineages
GET {{address}}/pipelines/h3zp5icwqtlulkr1dxogua152roahpzu/lineage HTTP/1.1

### Get lineages
GET {{address}}/pipelines/h3zp5icwqtlulkr1dxogua152roahpzu/lineage/qdjs5q9f5b93qfhubkri4k46rg2dp9s8ay5v5h9aexbmfecustgavc8oewktwb9o HTTP/1.1


@manager_address = http://localhost:3001
### Get dataset
GET {{manager_address}}/pipelines/rfkkxb5vlc80lwcgqjdfeub8gdtw0g0o HTTP/1.1

### Get pipeline executions
GET {{manager_address}}/pipelines HTTP/1.1

### Get status
GET {{manager_address}}/pipelines/ny84rq3vrpept5g5ufmikr3hpgfcorjd/status HTTP/1.1

### Delete specific pipeline
DELETE {{manager_address}}/pipelines/h3zp5icwqtlulkr1dxogua152roahpzu HTTP/1.1


### Purge specific pipeline
DELETE {{manager_address}}/pipelines/h3zp5icwqtlulkr1dxogua152roahpzu/purge HTTP/1.1

### Purge specific pipeline
DELETE {{address}}/pipelines/5dwts5tsuoujbjdrcmpgt5t5qqcn2cr2/results HTTP/1.1




### Delete pipeline
DELETE {{manager_address}}/pipelines HTTP/1.1

### Delete queues
GET {{manager_address}}/delete_queues HTTP/1.1