@address = http://localhost:3000
@dataset_path = test_dataset
@initial_commit_hash = initial_commit
@commit_hash = 4
@branch_hash = initial_branch
@file = cat.1.jpg

### Delete dataset
DELETE {{address}}/{{dataset_path}} HTTP/1.1

### Get pipeline
GET {{address}}/{{dataset_path}}/pipeline_result/2 HTTP/1.1


### Create pipeline result
POST {{address}}/{{dataset_path}}/pipeline_result HTTP/1.1
content-type: application/json

{
  "hash": "pipelinehash",
  "dataset_hash": "test_dataset",
  "commit_hash": "UrcbM2vN57Z8rLoA7u8DhqkYhMbUFmwQ",
  "files": []
}

